# MTH 4480 HW4
Devon DeJohn, Fall 2019

## Exercise 1
> Explain the differences between (discrete) data fitting and approximating a given function

Data fitting involves approximating a function at all points, whereas approximating a function involves matching exact values of points along an unknown curve.


## Exercise 2
> What are basis functions? Does an approximant $v(x)$ that is written as a linear combination of basis functions have to be linear in $x$?

Basis functions comprise what is called a function space, wherein any function in the space can be represented in terms of linear combinations of the basis functions. The set of all cubic polynomials represents such a function space, and its basis functions can be taken in linear combinations to represent any cubic polynomial that exists. Some arbitrary $v(x)$ then does not necessarily itself need to be a linear function.


## Exercise 3
> State one advantage and two disadvantages of using the monomial basis for polynomial interpolation.

Monomial interpolation is simple to setup, but is computationally expensive. Another major disadvantage is in the relatively limited monomial, where translations along the x-axis cannot occur (this would produce a binomial), e.g., $(x-3)^2.$ This means we have to try to "reach" the points in our data set that are, in a sense, "anchored" at the origin. This leads to instability, and eventually monomials become useless for interpolating among many data points.


## Exercise 4
> What are Lagrange Polynomials? How are they used for polynomial interpolation?

Lagrange polynomials form another basis from which we can construct linear combinations in order to interpolate between data points.


## Exercise 5
> State the main advantages and the main disadvantage for using the Lagrange representation.

Lagrange interpolation is still straight-forward to setup, if a little tedious. Mainly its strength is in computational efficiency. However, if the spacing is too large between points Lagrange interpolation incurs large errors. Additionally, for evenly spaced points the Lagrange form will tend to oscillate, suffering from something called *Runge's phenomenon.* This is caused in part by the large derivatives you obtain from higher-order polynomials. It is similar to *Gibb's phenomenon* which occurs in Fourier series approximations. 


## Exercise 6
> State two advantages and two disadvantages for using the Newton representation for polynomial interpolation.

The construction of Newton polynomials is slightly more computationally expensive than in Lagrange interpolation. Its main advantage is in its adaptability; in the other interpolation methods if a new data point is added the entire polynomial must be reconstructed. Newton's method allows for simply adding the new data point and tacking on another standalone Newton polynomial which includes it.


## Exercise 7
> Describe the connection between the $kth$ divided difference of a function $f$ and its $kth$ derivatve.

When the data points are equispaced, the $kth$ divided difference approximates the $kth$ derivative of the function in the typical quotient rule form for the slope of the function between $x$ and $x+h.$ The smaller the distance between the points, the more accurately approximated is the $kth$ derivative.


## Exercise 8
> (Monomial) Derive the linear interpolant through the two data points $(1.0,2.0)$ and $(1.1, 2.5).$ Then derive the quadratic interpolant by adding the point $(1.2, 1.5).$ Show a graph depicting this situation

Let $M_1(x) = c_0 + c_1 x$ and we have $M_1(1) = c_0 + c_1 = 2$ and $M_1(1.1) = c_0 + 1.1 c_1 = 2.5.$ Let $A$ be the matrix of coefficents on the constants $c_0, c_1,$ and then we can solve the linear equation,

$$
\begin{bmatrix}
1 & 1 \\
1 & 1.1
\end{bmatrix}\begin{bmatrix}c_0\\c_1\end{bmatrix} = \begin{bmatrix}2\\2.5\end{bmatrix} 
$$

$\det{A} = 0.1,$ and so $A^{-1} = \begin{bmatrix}11 & -10 \\ -10 & 10\end{bmatrix}$ and then we have

\begin{align}
\begin{bmatrix}11 & -10 \\ -10 & 10\end{bmatrix}
\begin{bmatrix}1 & 1 \\1 & 1.1\end{bmatrix}
\begin{bmatrix}c_0\\c_1\end{bmatrix} &= \begin{bmatrix}11 & -10 \\ -10 & 10\end{bmatrix}\begin{bmatrix}2\\2.5\end{bmatrix} \\
\begin{bmatrix}c_0\\c_1\end{bmatrix} &= \begin{bmatrix}22-25\\-20 + 25\end{bmatrix} \\
\begin{bmatrix}c_0\\c_1\end{bmatrix} &= \begin{bmatrix}-3\\5\end{bmatrix}
\end{align}

And so $M_1(x) = -3 + 5x.$

By the exact same process, we can find the quadratic polynomial $M_2(x) = c_0 + c_1 x + c_2 x^2,$

\begin{align}
M_2(1) &= c_0 + c_1 + c_2 = 2 \\
M_2(1.1) &= c_0 + 1.1 c_1 + 1.21 c_2 = 2.5 \\
M_2(1.2) &= c_0 + 1.2 c_1 + 1.44 c_2 = 1.5
\end{align}

Which gives the matrix equation

$$
\begin{bmatrix}
1 & 1 & 1\\
1 & 1.1 & 1.21 \\
1 & 1.2 & 1.44
\end{bmatrix}
\begin{bmatrix} c_0 \\ c_1 \\ c_2\end{bmatrix} =
\begin{bmatrix} 2 \\ 2.5 \\ 1.5 \end{bmatrix}
$$

With the solution

$$
\begin{bmatrix} c_0 \\ c_1 \\ c_2\end{bmatrix} =
\begin{bmatrix} -85.5 \\ 162.5 \\ -75 \end{bmatrix}
$$


And the graph of our two monomial interpolants,

![](https://i.imgur.com/fJsvoG5.png)

When I was checking to make sure I had calculated my matrix equations properly, I saw that even with these simple calculations, computers immediately incur roundoff error:

```julia
julia> a = [1 1; 1 1.1]
2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.1

julia> b = [2 ; 2.5]
2-element Array{Float64,1}:
 2.0
 2.5

julia> a\b
2-element Array{Float64,1}:
 -2.9999999999999956
  4.999999999999996
```


## Exercise 9
> (Lagrange) Use the known values of the function $\sin(x)$ at $x=0,\frac{\pi}{6}, \frac{\pi}{4}, \frac{\pi}{3}, \frac{\pi}{2}$ to derive an interpolating polynomial $p(x).$ What is the degree of your polynomial? What is the interpolation error magnitude $|p(1.2) - \sin(1.2)|$?

Since the first coefficient is $f(x_0)=0,$ we will have $\mathscr{L}_0=0$ and so I will not bother constructing the basis polynomial for that term. Our Lagrange polynomials are:

\begin{align}
y_0 &= 0 &\mathscr{L}_0 &= 0 \\
y_1 &= \frac{1}{2} &\mathscr{L}_1 &= \frac{(x-0)(x-\frac{\pi}{4})(x-\frac{\pi}{3})(x-\frac{\pi}{2})}{(\frac{\pi}{6}-0)(\frac{\pi}{6}-\frac{\pi}{4})(\frac{\pi}{6}-\frac{\pi}{3})(\frac{\pi}{6}-\frac{\pi}{2})} \\
y_2 &= \frac{\sqrt{2}}{2} &\mathscr{L}_2 &= \frac{(x-0)(x-\frac{\pi}{6})(x-\frac{\pi}{3})(x-\frac{\pi}{2})}{(\frac{\pi}{4}-0)(\frac{\pi}{4}-\frac{\pi}{6})(\frac{\pi}{4}-\frac{\pi}{3})(\frac{\pi}{4}-\frac{\pi}{2})} \\
y_3 &= \frac{\sqrt{3}}{2} &\mathscr{L}_3 &= \frac{(x-0)(x-\frac{\pi}{6})(x-\frac{\pi}{4})(x-\frac{\pi}{2})}{(\frac{\pi}{3}-0)(\frac{\pi}{3}-\frac{\pi}{6})(\frac{\pi}{3}-\frac{\pi}{4})(\frac{\pi}{3}-\frac{\pi}{2})} \\
y_4 &= 1 &\mathscr{L}_4 &= \frac{(x-0)(x-\frac{\pi}{6})(x-\frac{\pi}{4})(x-\frac{\pi}{3})}{(\frac{\pi}{2} - 0)(\frac{\pi}{2} - \frac{\pi}{6})(\frac{\pi}{2} - \frac{\pi}{4})(\frac{\pi}{2} - \frac{\pi}{3})}
\end{align}

This will result in the fourth-degree polynomial (I used Wolfram Alpha to expand and simplify the basis polynomials),

\begin{align}
p(x) = \frac{1}{2}\left(\frac{54 x}{\pi} - \frac{486 x^2}{\pi^2} + \frac{1404 x^3}{\pi^3} - \frac{1296 x^4}{\pi^4}\right) &+ \frac{\sqrt{2}}{2}\left( -\frac{64 x}{\pi} + \frac{704 x^2}{\pi^2} - \frac{2304 x^3}{\pi^3} + \frac{2304 x^4}{\pi^4} \right) + \\
\frac{\sqrt{3}}{2}\left( \frac{27 x}{\pi} - \frac{324 x^2}{\pi^2} + \frac{1188 x^3}{\pi^3} - \frac{1296 x^4}{\pi^4}\right) &+ 1\left( -\frac{2 x}{\pi} + \frac{26 x^2}{\pi^2} - \frac{108 x^3}{\pi^3} + \frac{144 x^4}{\pi^4}\right)
\end{align}

Evaluating $p(x)$ at $x=1.2$ gives $0.9321449$ and so the error is $|p(1.2)-\sin(1.2)| = 0.000105814.$

## Exercise 10
> (Divided Differences) For some function $f$, you have a table of divided differences of the form

| $i$ | $z_i$    | $f[\cdot]$    | $f[\cdot, \cdot]$ | $f[\cdot, \cdot, \cdot]$ | $f[\cdot, \cdot, \cdot, \cdot]$ |
| :-: | :---: | :------: | :-----------: | :----------------: | :-: |
| $0$ | $5.0$ | $f[z_0]$ |               |                    | |
| $1$ | $5.0$ | $f[z_1]$ | $f[z_0, z_1]$ |                    | |
| $2$ | $6.0$ | $4.0$    | $5.0$         | $-3.0$             | |
| $3$ | $4.0$ | $2.0$    | $f[z_2, z_3]$ | $f[z_1, z_2, z_3]$ | $f[z_0, z_1, z_2, z_3]$ |

> Then construct the polynomial approximation using divided differences.


Completing the table (and noting that the first divided difference is actually an exact derivative),

| $i$ | $z_i$    | $f[z_i]$    | $f[z_{i-1}, z_i]$ | $f[z_{i-2}, z_{i-1}, z_i]$ | $f[z_{i-3}, z_{i-2}, z_{i-1}, z_i]$ |
| :-: | :---: | :------: | :-----------: | :----------------: | :----: |
| $0$ | $5.0$ | $-1.0$ |               |                    |        |
| $1$ | $5.0$ | $-1.0$ | $8.0$         |                    |        |
| $2$ | $6.0$ | $4.0$    | $5.0$         | $-3.0$             |        |
| $3$ | $4.0$ | $2.0$    | $1.0$         | $4.0$              | $-7.0$ |


And the resulting polynomial,

\begin{align}
p(x) &= -1(x-0)+8(x-0)(x-5)-3(x-0)(x-5)(x-6)-7(x-0)(x-5)(x-6)(x-4) \\
&= -7 x^4 + 102 x^3 - 477 x^2 + 709 x
\end{align}

## Exercise 11
> Comment on your results in the previous three problems.

Lagrange is a pain to do by hand. Monomial for a $2\times2$ matrix was very simple and quick but obviously intractible for larger matrices. Divided differences is quite simple to put together, if a little tedious (and of course this felt like a bit of a trick question so it took me a while to understand how to fill in the last value).